SheetLog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('account_control.urls')),
    path('stock/',include('stock.urls')),
    path('account/',include('account_control.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
]

stock/urls.py
from django.urls import  path
from . import views
from stock.views.Item import views as item_views
from stock.views.Top_up import views as top_up_views
from stock.views.display import views as display_views
from stock.views.statement import views as statement_views
from stock.views.temp import views as temp_views
from datetime import datetime
app_name='stock'
urlpatterns=[
    # Display
    path('',display_views.IndexView,name='index'),


    # Item
    path('item/create/',item_views.CreateView,name='create_item'),
    path('item/list/',item_views.ListView,name='list_item'),
    path('item/edit/<int:pk>/',item_views.EditView,name='edit_item'),

    # topup
    path('topup/',top_up_views.Top_up_View,name='create_top_up'),
    path('topup/list/',top_up_views.Top_up_List_View,name='list_top_up'),
    path('topup/edit/<int:pk>',top_up_views.Top_up_Edit_View,name='edit_top_up'),

    # statement
    path('create_statement/',statement_views.CreateView,name='create_statement'),
    path('list_income/',statement_views.ListIncomeView,name='list_income'),
    path('edit_income/<int:pk>/',statement_views.EditIncomeView,name='edit_income'),
    path('list_expense/',statement_views.ListExpenseView,name='list_expense'),
    path('edit_expense/<int:pk>/',statement_views.EditExpenseView,name='edit_expense'),

    # temp expense
    path('temp_create/',temp_views.CreateView,name='create_temp'),
    path('list_temp/',temp_views.ListView,name='list_temp'),
    path('edit_temp/<int:pk>',temp_views.EditView,name='edit_temp'),

]

stock/iryu/Display/views.py
from django.shortcuts import render, redirect
from stock.models import Item
from account_control.models import UserStart

from stock.iryu.Display.Data2View import Display


# Create your views here.
def IndexView(request):
    if not request.user.is_authenticated:
        return redirect('account_control:index')
    # if login check if item Exist
    # check if login with admin
    elif UserStart.objects.filter(username=request.user).count() == 0:
        return redirect('account_control:logout')
    else:
        if request.POST:  # if Post Update data
            content = Display.setdisplay(Display,request)
            return render(request,'stock/display/index.html',content)

        else:  # login and get view list
            if Item.objects.all().count() == 0:
                return redirect('stock:create_item')  # send to create item
            else:
                content = Display.getdisplay(Display, request)
                return render(request, 'stock/display/index.html', content)

stock/iryu/Item/views.py
from django.shortcuts import render, redirect
from stock.models import Item
from stock.iryu.Item.Data2View import data2view
from account_control.iryu.script import is_superior


def CreateView(request):
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    content = {}
    if request.method == 'POST':
        makenewitem = data2view.create(data2view, request)
        content['createnewitem'] = makenewitem
    return render(request, 'stock/Item/create.html', content)


def ListView(request):
    content = {
        'items': Item.objects.all()
    }

    return render(request, 'stock/Item/list.html', content)


def EditView(request, pk=None):
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    if id is not None:
        if request.POST:
            data2view.edit(data2view,request, pk)
        elif Item.objects.filter(id=pk).count() == 1:
            content = {'item': Item.objects.get(id=pk) }
            return render(request, 'stock/Item/edit.html', content)
    return redirect('stock:list_item')

stock/iryu/Top_up/views.py
from django.shortcuts import render,redirect
from stock.models import Item,TopUp
from stock.iryu.Top_up.Data2View import data2view
from account_control.iryu.script import is_superior


def Top_up_View(request):
    content = {'items': Item.objects.filter(type=3)}
    if request.POST:
        data2view.top_up(data2view,request)
        return redirect('stock:list_top_up')
    return render(request, 'stock/top_up/create.html', content)


def Top_up_List_View(request):
    content=data2view.list(data2view,request)
    return render(request, 'stock/top_up/list.html',content)


def Top_up_Edit_View(request,pk):
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    if TopUp.objects.filter(id=pk).count() == 1:
        if request.POST:
            data2view.edit(data2view,request,pk)
        else:
            content = {'top_up': TopUp.objects.get(id=pk)}
            return render(request, 'stock/top_up/edit.html', content)
    return redirect('stock:list_top_up')

stock/iryu/statement/views.py
from django.shortcuts import render,redirect
from stock.models import Income,Expense
from account_control.models import UserStart
from .create import create,edit,editexpense
from account_control.iryu.script import is_superior
def CreateView(request):
    if request.POST:
        result = create(request)
        if result == 'success-income':
            return redirect('stock:list_income')
        elif result == 'success-expense':
            return redirect('stock:list_expense')
        else:
            return render(request,'stock/statement/create.html',result)
    return render(request,'stock/statement/create.html')

def ListIncomeView(request):
    worker = UserStart.objects.get(username=request.user)
    income = Income.objects.filter(date_log__gt=worker.date_log)
    content = {'incomes': income}
    return render(request,'stock/statement/list_income.html',content)


def ListExpenseView(request):
    worker = UserStart.objects.get(username=request.user)
    expense = Expense.objects.filter(date_log__gt=worker.date_log)
    content = {'expenses': expense}
    return render(request,'stock/statement/list_expense.html',content)


def EditIncomeView(request,pk):
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    income = Income.objects.get(id=pk)
    content = {'income': income}
    if Income.objects.filter(id=pk).count() == 0:
        return redirect('stock:list_income')
    if request.POST:
        result = edit(request)
        if result == 'updated' or result == 'deleted':
            return redirect('stock:list_income')
        else:
            content['message'] = result
    return render(request,'stock/statement/edit_income.html',content)

def EditExpenseView(request,pk):
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    expense = Expense.objects.get(id=pk)
    content = {'expense': expense}
    if Expense.objects.filter(id=pk).count() == 0:
        return redirect('stock:list_expense')
    if request.POST:
        result = editexpense(request)
        if result == 'updated' or result == 'deleted':
            return redirect('stock:list_expense')
        else:
            content['message'] = result
    return render(request,'stock/statement/edit_expense.html',content)

stock/scripts/Item/views.py
from django.shortcuts import render, redirect
from stock.models import Item
from stock.scripts.Item.Data2View import create,edit
from account_control.scripts.script import is_superior


def CreateView(request):
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    content = {}
    if request.method == 'POST':
        makenewitem = create(request)
        content['createnewitem'] = makenewitem
    return render(request, 'stock/Item/create.html', content)


def ListView(request):
    content = {
        'items': Item.objects.all()
    }

    return render(request, 'stock/Item/list.html', content)


def EditView(request, pk=None):
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    if id is not None:
        if request.POST:
            edit(request, pk)
        elif Item.objects.filter(id=pk).count() == 1:
            content = {'item': Item.objects.get(id=pk) }
            return render(request, 'stock/Item/edit.html', content)
    return redirect('stock:list_item')

stock/scripts/Top_up/views.py
from django.shortcuts import render,redirect
from stock.models import Item,TopUp
from stock.scripts.Top_up.Data2View import list,top_up,edit
from account_control.scripts.script import is_superior


def Top_up_View(request):
    content = {'items': Item.objects.filter(type=3)}
    if request.POST:
        top_up(request)
        return redirect('stock:list_top_up')
    return render(request, 'stock/top_up/create.html', content)


def Top_up_List_View(request):
    content = list(request)
    return render(request, 'stock/top_up/list.html',content)


def Top_up_Edit_View(request,pk):
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    if TopUp.objects.filter(id=pk).count() == 1:
        if request.POST:
            edit(request,pk)
        else:
            content = {'top_up': TopUp.objects.get(id=pk)}
            return render(request, 'stock/top_up/edit.html', content)
    return redirect('stock:list_top_up')

stock/scripts/display/views.py
from django.shortcuts import render, redirect
from stock.models import Item
from account_control.models import UserStart
from . import Data2View
from .function import calculater
from datetime import datetime
from stock.forms import InputTest


def IndexView(request):
    end_retrieve = datetime.now()
    if not request.user.is_authenticated:
        return redirect('account_control:index')
    # if login check if item Exist
    # check if login with admin
    elif UserStart.objects.filter(username=request.user).count() == 0:
        return redirect('account_control:logout')
    else:
        if request.POST:  # if Post Update data
            content = Data2View.setdisplay(request)
            return render(request, 'stock/display/index.html', content)

        else:  # login and get view list
            if Item.objects.all().count() == 0:
                return redirect('stock:create_item')  # send to create item
            else:
                content = calculater.normal_get_log(request)
                return render(request, 'stock/display/index.html', content)


def getDateView(request):
    form = InputTest()
    content = {
        'form': form
    }

    if request.POST:
        result = calculater.text2date(request)
        if result is not 'fail':
            content = result
            return render(request,'stock/display/index.html',content)
        else:
            content['errors']=result
    return render(request,'stock/display/getdate.html',content)

stock/views.py
# Move to stock/iryu folder

stock/views/Item/views.py
from django.shortcuts import render, redirect
from stock.models import Item
from stock.views.Item.Data2View import create,edit
from account_control.scripts.script import is_superior,account_permit


def CreateView(request):
    account_permit(request)
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    content = {}
    if request.method == 'POST':
        makenewitem = create(request)
        content['createnewitem'] = makenewitem
    return render(request, 'stock/Item/create.html', content)


def ListView(request):
    account_permit(request)
    content = {
        'items': Item.objects.all()
    }

    return render(request, 'stock/Item/list.html', content)


def EditView(request, pk=None):
    account_permit(request)
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    if id is not None:
        if request.POST:
            edit(request, pk)
        elif Item.objects.filter(id=pk).count() == 1:
            content = {'item': Item.objects.get(id=pk) }
            return render(request, 'stock/Item/edit.html', content)
    return redirect('stock:list_item')

stock/views/Top_up/views.py
from django.shortcuts import render,redirect
from stock.models import Item,TopUp
from stock.views.Top_up.Data2View import list,top_up,edit
from account_control.scripts.script import is_superior


def Top_up_View(request):
    content = {'items': Item.objects.filter(type=3)}
    if request.POST:
        top_up(request)
        return redirect('stock:list_top_up')
    return render(request, 'stock/top_up/create.html', content)


def Top_up_List_View(request):
    content = list(request)
    return render(request, 'stock/top_up/list.html',content)


def Top_up_Edit_View(request,pk):
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    if TopUp.objects.filter(id=pk).count() == 1:
        if request.POST:
            edit(request,pk)
        else:
            content = {'top_up': TopUp.objects.get(id=pk)}
            return render(request, 'stock/top_up/edit.html', content)
    return redirect('stock:list_top_up')

stock/views/display/views.py
from django.shortcuts import render, redirect
from stock.models import Item
from account_control.models import UserStart
from .function import calculater,data2view
from django.utils import timezone
from account_control.scripts import script


def IndexView(request):
    if not script.account_permit(request):  # check user permit before do other thing
        return redirect('account_control:logout')
    if request.POST:  # if Post Update data
        if 'startdate' in request.POST:
            content = calculater.text2date(request)
            return render(request, 'stock/display/index.html', content)
        else:
            content = data2view.setdisplay(request)
            return render(request, 'stock/display/index.html', content)

    else:  # login and get view list
        if Item.objects.all().count() == 0:
            return redirect('stock:create_item')  # send to create item
        else:
            content = calculater.normal_get_log(request)
            return render(request, 'stock/display/index.html', content)

stock/views/statement/views.py
from django.shortcuts import render,redirect
from stock.models import Income,Expense
from account_control.models import UserStart
from .create import create,edit,editexpense
from account_control.scripts.script import is_superior


def CreateView(request):
    if request.POST:
        result = create(request)
        if result == 'success-income':
            return redirect('stock:list_income')
        elif result == 'success-expense':
            return redirect('stock:list_expense')
        else:
            return render(request,'stock/statement/create.html',result)
    return render(request,'stock/statement/create.html')


def ListIncomeView(request):
    worker = UserStart.objects.get(username=request.user)
    income = Income.objects.filter(date_log__gt=worker.date_log)
    content = {'incomes': income}
    return render(request,'stock/statement/list_income.html',content)


def ListExpenseView(request):
    worker = UserStart.objects.get(username=request.user)
    expense = Expense.objects.filter(date_log__gt=worker.date_log)
    content = {'expenses': expense}
    return render(request,'stock/statement/list_expense.html',content)


def EditIncomeView(request,pk):
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    income = Income.objects.get(id=pk)
    content = {'income': income}
    if Income.objects.filter(id=pk).count() == 0:
        return redirect('stock:list_income')
    if request.POST:
        result = edit(request)
        if result == 'updated' or result == 'deleted':
            return redirect('stock:list_income')
        else:
            content['message'] = result
    return render(request,'stock/statement/edit_income.html',content)


def EditExpenseView(request,pk):
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    expense = Expense.objects.get(id=pk)
    content = {'expense': expense}
    if Expense.objects.filter(id=pk).count() == 0:
        return redirect('stock:list_expense')
    if request.POST:
        result = editexpense(request)
        if result == 'updated' or result == 'deleted':
            return redirect('stock:list_expense')
        else:
            content['message'] = result
    return render(request,'stock/statement/edit_expense.html',content)

stock/views/temp/views.py
from django.shortcuts import redirect,render
from .create import create
from account_control.models import UserStart
from stock.models import TempExpense
from .create import edit

def CreateView(request):
    content = {}
    if request.POST:
        result = create(request)
        if result == 'success':
            return redirect('stock:list_temp')
        else:
            content['message'] = result
    return render(request,'stock/temp/create.html',content)


def ListView(request):
    worker = UserStart.objects.get(username=request.user)
    data = TempExpense.objects.filter(date_log__gt=worker.date_log)
    content ={
        'temps': data
    }
    return render(request,'stock/temp/list_temp.html',content)


def EditView(request,pk):
    content = {'temp_id':pk}
    if TempExpense.objects.filter(id=pk).count() == 0:
        return redirect('stock:list_temp')
    else:
        content['temp'] = TempExpense.objects.get(id=pk)
    if request.POST:
        result = edit(request)
        if result == 'updated' or result == 'deleted':
            return redirect('stock:list_temp')
        else:
            content['message'] = result
    return render(request,'stock/temp/edit_temp.html',content)

stock/templates/stock/statement/create.html
{% extends 'stock/layout.html' %}
{%block content%}
{% if message %}
<div class="alert alert-danger" role="alert">
  {{message}}
</div>
{% endif %}
<div class="container">
<form class="form" action="" method="post">
    {% csrf_token %}
    <div class="content-group">
        <label class="form-control-label">รายการ</label>
        <input class="form-control form-control-lg" name="name" />
    </div>
    <div class="content-group">
        <label class="form-control-label">ยอดเงิน</label>
        <input class="form-control form-control-lg" type="number" name="value" />
    </div>
    <div class="content-group">
        <label class="form-control-label">ประเภท</label>
        <select class="form-control form-control-lg" name="record_type" type="number">
            <option value="none">ประเภท</option>
            <option value=1>รายรับ</option>
            <option value=2>รายจ่าย</option>
        </select>
    </div>
<button type="submit" >บันทึก</button>
</form>
</div>

{% endblock%}

stock/templates/stock/statement/edit_expense.html
{% extends 'stock/layout.html'%}
{%block content%}
{% if message %}
<div class="alert alert-danger">{{message}}</div>
{% endif %}
{% if expense %}
<div class="container">
    <div class="col-md-8">

<form action="" method="post">
    {%csrf_token%}
    <input  type="hidden" name="expense_id" value="{{expense.id}}" />
    <div class="content-grop">
        <label class="form-control-label" name="{{expense.name}}"><h1>{{expense.name}}</h1></label>
    <input name="value" TYPE="number" class="form-control form-control-lg" value="{{expense.value}}" />
    </div>
    <div class="content-group">
        <label class="form-control-label" ><H3>Record Date</H3></label>
        <label class="form-control form-control-lg">{{expense.date_log}}</label>
    </div>
    <button class="btn btn-success" type="submit" name="update">Update</button>

        <a  class="btn btn-dark" href="{%url 'stock:list_expense'%}">Cancel</a>
    <div class="form-group">
        <label class="label label-danger">ลบสินค้าออกจาก ฐานข้อมูล</label><br>
        <input type="submit" name="DELETE" class="btn btn-danger" value="ลบ {{expense.name }}">
    </div>
</form>
{% endif %}
    </div>
</div>

{%endblock%}

stock/templates/stock/statement/edit_income.html
{% extends 'stock/layout.html'%}
{%block content%}
{% if message %}
<div class="alert alert-danger">{{message}}</div>
{% endif %}
{% if income %}
<div class="container">
    <div class="col-md-8">

<form action="" method="post">
    {%csrf_token%}
    <input  type="hidden" name="income_id" value="{{income.id}}" />
    <div class="content-grop">
        <label class="form-control-label" name="{{income.name}}"><h1>{{income.name}}</h1></label>
    <input name="value" TYPE="number" class="form-control form-control-lg" value="{{income.value}}" />
    </div>
    <div class="content-group">
        <label class="form-control-label" ><H3>Record Date</H3></label>
        <label class="form-control form-control-lg">{{income.date_log}}</label>
    </div>
    <button class="btn btn-success" type="submit" name="update">Update</button>

        <a  class="btn btn-dark" href="{%url 'stock:list_income'%}">Cancel</a>
    <div class="form-group">
        <label class="label label-danger">ลบสินค้าออกจาก ฐานข้อมูล</label><br>
        <input type="submit" name="DELETE" class="btn btn-danger" value="ลบ {{income.name }}">
    </div>
</form>
{% endif %}
    </div>
</div>

{%endblock%}

stock/templates/stock/statement/list_expense.html
{% extends 'stock/layout.html' %}
{% block content %}
<div class="container">
{% if expenses %}
    <table class="table">
      <tr>
        <th>วันที่</th>
        <th>รายการ</th>
        <th>จำนวน</th>
        <th>แก้ไข</th>
      </tr>
      {% for expense in expenses %}
      <tr>
        <td>{{expense.date_log}}</td>
        <td>{{expense.name}}</td>
        <td>{{expense.value}}</td>
        <td><a href="{% url 'stock:edit_expense' expense.id %}"><button>Edit</button></a></td>
      </tr>
      {% endfor %}
{% endif %}
    <tr>
        <td>
            <a class="btn btn-success" href="{% url 'stock:create_statement' %}">เพิ่มรายการ</a>
        </td>

    </tr>



</table>
{% endblock %}

stock/templates/stock/statement/list_income.html
{% extends 'stock/layout.html' %}
{% block content %}
<div class="container">
{% if incomes %}
    <table class="table">
      <tr>
        <th>วันที่</th>
        <th>รายการ</th>
        <th>จำนวน</th>
        <th>แก้ไข</th>
      </tr>
      {% for income in incomes %}
      <tr>
        <td>{{income.date_log}}</td>
        <td>{{income.name}}</td>
        <td>{{income.value}}</td>
        <td><a href="{% url 'stock:edit_income' income.id %}"><button>Edit</button></a></td>
      </tr>
      {% endfor %}
{% endif %}
    <tr>
        <td>
            <a class="btn btn-success" href="{% url 'stock:create_statement' %}">เพิ่มรายการ</a>
        </td>

    </tr>



</table>
{% endblock %}